# Default settings for rustfmt
edition = "2021"  # Specify your Rust edition
max_width = 100   # Maximum line width
tab_spaces = 4    # Number of spaces per tab
newline_style = "Unix"  # Line ending style
reorder_modules = true  # Reorder module declarations
reorder_imports = true
reorder_impl_items = false
indent_style = "Block"
normalize_comments = false
imports_granularity = "Module"
group_imports = "StdExternalCrate"
